:hide-uri-scheme:
:doctype: book

:site_resource: .
include::{site_resource}/pj-settings.adoc[opts=optional]
include::{site_resource}/adoc-cmmn-all.adoc[opts=optional]

:source-highlighter: highlight.js

= {pj_gh_repo}
:toc: preamble
:toclevels: 2

{pj_ps_license_img}
{pj_ps_release_img}
{pj_ps_langtop_img}
{pj_ps_langcount_img}
{pj_ps_issues_img}


== Description

A sonar-scanner for PHP using composer.

On the hunt for a Sonar scanner which is provided by composer, I didn't found any library which was working or had the current version of the scanner.
So I decided to write a new library.

The library is tested with Windows and Windows with Cygwin, so it will (hopefully) work with Linux also. 
Unfortunately I am not able to test the library with MacOs. So link:./issues[let me know], if and what is not working.

== Configuration

Please read the link:docu-config.adoc[configuration].

== Usage

include::{site_resource}/pj-usage.adoc[opts=optional]

== Additional Information

* link:docu-commands.adoc[Composer Commands] - New commands for composer

== Reference
* link:https://getcomposer.org/[Composer]

_{pj_cright_author}_
