:hide-uri-scheme:
:doctype: book

:site_resource: .
include::{site_resource}/pj-settings.adoc[opts=optional]
include::{site_resource}/adoc-cmmn-all.adoc[opts=optional]

:source-highlighter: highlight.js

= {pj_gh_repo}
:toc: preamble
:toclevels: 2

{pj_ps_license_img}
{pj_ps_release_img}
{pj_ps_langtop_img}
{pj_ps_langcount_img}
{pj_ps_issues_img}

{cm_shlds_tool_phpunit_img}
{cm_shlds_tool_sonarcloud_img}
{cm_shlds_tool_cdcy_img}
{cm_shlds_tool_cvrlls_img}

image:{cm_shlds_tool_phpcsfixer_url}[title="PHP CS Fixer Ruleset"]
image:{cm_shlds_tool_phpstan_url}[title="PHPStan Level"]
image:{cm_shlds_tool_psalm_url}[title="Psalm Level"]
image:{cm_shlds_tool_phpcs_url}[title="PHP CodeSniffer Ruleset""]
image:{cm_shlds_tool_phpmd_url}[title="PHP Mess Detector Ruleset"]

== Description

A sonar-scanner for PHP using composer.

On the hunt for a Sonar scanner which is provided by composer, I didn't found any library which was working or had the current version of the scanner.
So I decided to write a new library.

The library is tested with Windows and Windows with Cygwin, so it will (hopefully) work with Linux also. 
Unfortunately I am not able to test the library with MacOs. So link:./issues[let me know], if and what is not working.

== Configuration

Please read the link:docu-config.adoc[configuration].

== Usage

include::{site_resource}/pj-usage.adoc[opts=optional]

== Project Status

Please read the link:docu-analysis.adoc[project status].

== Additional Information

* link:docu-commands.adoc[Composer Commands] - New commands for composer

== Notice

link:{pj_snr_dash_url}[image:{cm_snr_tool_sonarcloud_url}[title="Sonarcloud Logo"]]

== Reference
* link:https://getcomposer.org/[Composer]

_{pj_cright_author}_
